site_name: Budget Dance
site_dir: via/docu
use_directory_urls: false

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png

nav:
  - Home: index.md
  - Workbook: 
    - workbook.md
    - Worksheets:
      - "Index of worksheets": worksheets.md
      - "Accounts & Balances":
        - Accounts: sheets/accounts.md
        - Balances: sheets/balances.md
        - "Transfers plan": sheets/transfers_plan.md
      - "Income, Expense & Cashflow":
        - "All years": sheets/iande.md
        - "Current year": sheets/current.md
        - "Auxiliary calculations": sheets/aux.md
        - "Impact of investments": sheets/invest_iande_work.md
      - Retirement: 
        - "Income & medical plan": sheets/retirement.md
        - "Retirement parameters": sheets/retireparms.md
      - "Various Actuals":
        - "Investments Actuals": sheets/invest_actl.md
        - "Transfers Actuals": sheets/transfers_actl.md
        - "Other Actuals": sheets/other_actl.md
      - taxes:
        - "Tax tables": sheets/tax_tables.md
        - "Capital gains": sheets/cap_gain.md
        - Taxes: sheets/taxes.md
      - "General": sheets/gen_tables.md
      - Utility: sheets/utility.md
    - Formulas:
      - "Helpers (Lambdas)": functions/excel_lambdas.md
      - Idioms: idioms.md
      - Anti-patterns: anti_patterns.md
  - Data: 
    - "Data files": data_files.md
    - "Report definitions": report_configs.md
    - "Accounting notes": accounting.md
    - "Validation": validation.md
  - Configuration & deployment:
    - Summary: configuration_summary.md
    - Libraries: libraries.md
    - "API Key": configure_api.md
    - "Configuration control file": configuration.md
    - "Python environment": python.md
    - "Deployment": deployment.md
  - Operations: 
    - "Export/Import Cycle": operations.md
    - "Use cases": use_cases.md
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      line_spans: '__codeline'
  - pymdownx.superfences

      


      

